<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <UserSecretsId>6f7b9f84-b96d-4d9e-a7fa-097e46746e4a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Openapi" version="10.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RU.Uncio.Application\RU.Uncio.Application.csproj" />
    <ProjectReference Include="..\RU.Uncio.Domain\RU.Uncio.Domain.csproj" />
    <ProjectReference Include="..\RU.Uncio.Infrastructure\RU.Uncio.Infrastructure.csproj" />
  </ItemGroup>

</Project>
