{
 "title": "Events-API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "http_server_request_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_active_requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "http_server_request_duration_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}